# Generated by Django 4.1.4 on 2022-12-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=256)),
                ('order_id', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=256)),
                ('amount', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'default_date',
                'abstract': False,
            },
        ),
    ]
